import tailwindcssAnimate from 'tailwindcss-animate'
import typography from '@tailwindcss/typography'

/** @type {import('tailwindcss').Config} */
const config = {
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  darkMode: ['selector', '[data-theme="dark"]'],
  plugins: [tailwindcssAnimate, typography],
  prefix: '',
  safelist: [
    'lg:col-span-3',
    'lg:col-span-4',
    'lg:col-span-6',
    'lg:col-span-8',
    'lg:col-span-9',
    'lg:col-span-12',
    'border-border',
    'bg-card',
    'border-error',
    'bg-error/30',
    'border-success',
    'bg-success/30',
    'border-warning',
    'bg-warning/30',
    'min-h-[40vh]',
    'min-h-[60vh]',
    'min-h-[80vh]',
    'min-h-[100vh]',
    'max-h-[40vh]',
    'max-h-[60vh]',
    'max-h-[80vh]',
    'max-h-[100vh]',
    'bg-background',
    'bg-muted',
    'bg-accent',
    'bg-brand',
    'bg-primary',
    'bg-secondary',
    'pt-0',
    'pt-8',
    'pt-16',
    'pt-24',
    'pt-32',
    'pb-0',
    'pb-8',
    'pb-16',
    'pb-24',
    'pb-32',
    'opacity-0',
    'animate-fade-in',
    'animate-fade-in-up',
    'animate-fade-in-down',
    'animate-fade-in-left',
    'animate-fade-in-right',
    'animate-zoom-in',
    // Typography classes
    'font-inter',
    'font-roboto',
    'font-open-sans',
    'font-lato',
    'font-montserrat',
    'font-playfair',
    'font-merriweather',
    'font-poppins',
    'font-raleway',
    'font-source-sans',
    'text-foreground',
    'text-muted-foreground',
    'text-accent-foreground',
    'text-brand-foreground',
    'text-brand',
    'text-primary',
    'text-primary-foreground',
    'text-secondary',
    'text-secondary-foreground',
    'text-white',
    'text-black',
    // Heading color classes
    '[&_h1]:text-foreground',
    '[&_h2]:text-foreground',
    '[&_h3]:text-foreground',
    '[&_h4]:text-foreground',
    '[&_h5]:text-foreground',
    '[&_h6]:text-foreground',
    '[&_h1]:text-brand',
    '[&_h2]:text-brand',
    '[&_h3]:text-brand',
    '[&_h4]:text-brand',
    '[&_h5]:text-brand',
    '[&_h6]:text-brand',
    '[&_h1]:text-primary',
    '[&_h2]:text-primary',
    '[&_h3]:text-primary',
    '[&_h4]:text-primary',
    '[&_h5]:text-primary',
    '[&_h6]:text-primary',
    '[&_h1]:text-secondary',
    '[&_h2]:text-secondary',
    '[&_h3]:text-secondary',
    '[&_h4]:text-secondary',
    '[&_h5]:text-secondary',
    '[&_h6]:text-secondary',
    '[&_h1]:text-accent',
    '[&_h2]:text-accent',
    '[&_h3]:text-accent',
    '[&_h4]:text-accent',
    '[&_h5]:text-accent',
    '[&_h6]:text-accent',
    '[&_h1]:text-white',
    '[&_h2]:text-white',
    '[&_h3]:text-white',
    '[&_h4]:text-white',
    '[&_h5]:text-white',
    '[&_h6]:text-white',
    '[&_h1]:text-black',
    '[&_h2]:text-black',
    '[&_h3]:text-black',
    '[&_h4]:text-black',
    '[&_h5]:text-black',
    '[&_h6]:text-black',
  ],
  theme: {
    container: {
      center: true,
      padding: {
        '2xl': '2rem',
        DEFAULT: '1rem',
        lg: '2rem',
        md: '2rem',
        sm: '1rem',
        xl: '2rem',
      },
      screens: {
        '2xl': '86rem',
        lg: '64rem',
        md: '48rem',
        sm: '40rem',
        xl: '80rem',
      },
    },
    extend: {
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'fade-in': 'fadeIn 0.6s ease-out',
        'fade-in-up': 'fadeInUp 0.6s ease-out',
        'fade-in-down': 'fadeInDown 0.6s ease-out',
        'fade-in-left': 'fadeInLeft 0.6s ease-out',
        'fade-in-right': 'fadeInRight 0.6s ease-out',
        'zoom-in': 'zoomIn 0.6s ease-out',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      colors: {
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        background: 'hsl(var(--background))',
        border: 'hsla(var(--border))',
        brand: {
          DEFAULT: 'hsl(var(--brand))',
          foreground: 'hsl(var(--brand-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        foreground: 'hsl(var(--foreground))',
        input: 'hsl(var(--input))',
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        ring: 'hsl(var(--ring))',
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        success: 'hsl(var(--success))',
        error: 'hsl(var(--error))',
        warning: 'hsl(var(--warning))',
      },
      fontFamily: {
        mono: ['var(--font-geist-mono)'],
        sans: ['var(--font-geist-sans)'],
        inter: ['Inter', 'sans-serif'],
        roboto: ['Roboto', 'sans-serif'],
        'open-sans': ['Open Sans', 'sans-serif'],
        lato: ['Lato', 'sans-serif'],
        montserrat: ['Montserrat', 'sans-serif'],
        playfair: ['Playfair Display', 'serif'],
        merriweather: ['Merriweather', 'serif'],
        poppins: ['Poppins', 'sans-serif'],
        raleway: ['Raleway', 'sans-serif'],
        'source-sans': ['Source Sans Pro', 'sans-serif'],
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        fadeIn: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        fadeInUp: {
          from: { opacity: '0', transform: 'translateY(30px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        fadeInDown: {
          from: { opacity: '0', transform: 'translateY(-30px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        fadeInLeft: {
          from: { opacity: '0', transform: 'translateX(-30px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        fadeInRight: {
          from: { opacity: '0', transform: 'translateX(30px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        zoomIn: {
          from: { opacity: '0', transform: 'scale(0.95)' },
          to: { opacity: '1', transform: 'scale(1)' },
        },
      },
      typography: () => ({
        DEFAULT: {
          css: [
            {
              '--tw-prose-body': 'var(--text)',
              '--tw-prose-headings': 'var(--text)',
              h1: {
                fontWeight: 'normal',
                marginBottom: '0.25em',
              },
            },
          ],
        },
        base: {
          css: [
            {
              h1: {
                fontSize: '2.5rem',
              },
              h2: {
                fontSize: '1.25rem',
                fontWeight: 600,
              },
            },
          ],
        },
        md: {
          css: [
            {
              h1: {
                fontSize: '3.5rem',
              },
              h2: {
                fontSize: '1.5rem',
              },
            },
          ],
        },
      }),
    },
  },
}

export default config