/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    categories: Category;
    users: User;
    blocks: Block;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    blocks: BlocksSelect<false> | BlocksSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    header: Header;
    footer: Footer;
    settings: Setting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    height?: ('small' | 'medium' | 'large' | 'full' | 'auto') | null;
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout: (
    | CallToActionBlock
    | ColumnsBlock
    | ContentBlock
    | MediaBlock
    | ArchiveBlock
    | FormBlock
    | VideoBlock
    | TestimonialsBlock
    | TabsAccordionBlock
    | StatsBlock
    | TimelineBlock
    | BannerBlock
    | CodeBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  optimization?: {
    /**
     * Enable for above-the-fold images (hero images, etc.)
     */
    priority?: boolean | null;
    /**
     * Image quality (1-100). Lower = smaller file size.
     */
    quality?: number | null;
    /**
     * Delay loading until image is near viewport
     */
    lazyLoad?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Optional anchor ID for deep linking (e.g., "about-us" becomes #about-us)
   */
  blockAnchor?: string | null;
  backgroundColor?: ('none' | 'background' | 'card' | 'muted' | 'accent' | 'brand' | 'primary' | 'secondary') | null;
  /**
   * Control padding around this block
   */
  spacing?: {
    paddingTop?: ('none' | 'small' | 'medium' | 'large' | 'xlarge') | null;
    paddingBottom?: ('none' | 'small' | 'medium' | 'large' | 'xlarge') | null;
  };
  /**
   * Horizontal text alignment for content in this block
   */
  textAlignment?: ('left' | 'center' | 'right' | 'justify') | null;
  /**
   * Control when this block is visible
   */
  visibility?: {
    hidden?: boolean | null;
    /**
     * Block will be visible after this date/time
     */
    publishDate?: string | null;
    /**
     * Block will be hidden after this date/time
     */
    expiryDate?: string | null;
  };
  /**
   * Animation that plays when the block enters the viewport
   */
  animation?: ('none' | 'fadeIn' | 'fadeInUp' | 'fadeInDown' | 'fadeInLeft' | 'fadeInRight' | 'zoomIn') | null;
  /**
   * Override global typography settings for this block
   */
  typography?: {
    fontFamily?:
      | (
          | 'default'
          | 'geist-sans'
          | 'geist-mono'
          | 'inter'
          | 'roboto'
          | 'open-sans'
          | 'lato'
          | 'montserrat'
          | 'playfair-display'
          | 'merriweather'
          | 'poppins'
          | 'raleway'
          | 'source-sans-pro'
        )
      | null;
    headingFont?:
      | (
          | 'default'
          | 'geist-sans'
          | 'geist-mono'
          | 'inter'
          | 'roboto'
          | 'open-sans'
          | 'lato'
          | 'montserrat'
          | 'playfair-display'
          | 'merriweather'
          | 'poppins'
          | 'raleway'
          | 'source-sans-pro'
        )
      | null;
    textColor?:
      | (
          | 'default'
          | 'foreground'
          | 'muted-foreground'
          | 'accent-foreground'
          | 'brand-foreground'
          | 'brand'
          | 'primary'
          | 'primary-foreground'
          | 'secondary'
          | 'secondary-foreground'
          | 'white'
          | 'black'
        )
      | null;
    headingColor?:
      | (
          | 'default'
          | 'foreground'
          | 'brand'
          | 'primary'
          | 'secondary'
          | 'accent'
          | 'muted-foreground'
          | 'white'
          | 'black'
        )
      | null;
  };
  /**
   * Add custom Tailwind classes for advanced styling
   */
  customCSS?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ColumnsBlock".
 */
export interface ColumnsBlock {
  layout:
    | '50-50'
    | '33-67'
    | '67-33'
    | '40-60'
    | '60-40'
    | '30-70'
    | '70-30'
    | '25-75'
    | '75-25'
    | '33-33-33'
    | '25-25-25-25';
  /**
   * When columns stack on mobile, show them in reverse order
   */
  reverseOnMobile?: boolean | null;
  gap?: ('none' | 'small' | 'medium' | 'large' | 'xlarge') | null;
  /**
   * Add content to each column. The number of columns should match your layout choice.
   */
  columns?:
    | {
        contentType: 'richText' | 'media' | 'video' | 'code' | 'customHTML' | 'cta';
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        media?: (number | null) | Media;
        caption?: string | null;
        videoType?: ('youtube' | 'vimeo' | 'upload') | null;
        videoUrl?: string | null;
        videoUpload?: (number | null) | Media;
        code?: string | null;
        language?: ('typescript' | 'javascript' | 'css' | 'html' | 'json' | 'bash' | 'python') | null;
        /**
         * Paste your custom HTML or embed code (iFrames, widgets, etc.)
         */
        customHTML?: string | null;
        ctaText?: string | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        verticalAlignment?: ('top' | 'center' | 'bottom') | null;
        textAlign?: ('left' | 'center' | 'right') | null;
        padding?: ('none' | 'small' | 'medium' | 'large') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional anchor ID for deep linking (e.g., "about-us" becomes #about-us)
   */
  blockAnchor?: string | null;
  backgroundColor?: ('none' | 'background' | 'card' | 'muted' | 'accent' | 'brand' | 'primary' | 'secondary') | null;
  /**
   * Control padding around this block
   */
  spacing?: {
    paddingTop?: ('none' | 'small' | 'medium' | 'large' | 'xlarge') | null;
    paddingBottom?: ('none' | 'small' | 'medium' | 'large' | 'xlarge') | null;
  };
  /**
   * Horizontal text alignment for content in this block
   */
  textAlignment?: ('left' | 'center' | 'right' | 'justify') | null;
  /**
   * Control when this block is visible
   */
  visibility?: {
    hidden?: boolean | null;
    /**
     * Block will be visible after this date/time
     */
    publishDate?: string | null;
    /**
     * Block will be hidden after this date/time
     */
    expiryDate?: string | null;
  };
  /**
   * Animation that plays when the block enters the viewport
   */
  animation?: ('none' | 'fadeIn' | 'fadeInUp' | 'fadeInDown' | 'fadeInLeft' | 'fadeInRight' | 'zoomIn') | null;
  /**
   * Override global typography settings for this block
   */
  typography?: {
    fontFamily?:
      | (
          | 'default'
          | 'geist-sans'
          | 'geist-mono'
          | 'inter'
          | 'roboto'
          | 'open-sans'
          | 'lato'
          | 'montserrat'
          | 'playfair-display'
          | 'merriweather'
          | 'poppins'
          | 'raleway'
          | 'source-sans-pro'
        )
      | null;
    headingFont?:
      | (
          | 'default'
          | 'geist-sans'
          | 'geist-mono'
          | 'inter'
          | 'roboto'
          | 'open-sans'
          | 'lato'
          | 'montserrat'
          | 'playfair-display'
          | 'merriweather'
          | 'poppins'
          | 'raleway'
          | 'source-sans-pro'
        )
      | null;
    textColor?:
      | (
          | 'default'
          | 'foreground'
          | 'muted-foreground'
          | 'accent-foreground'
          | 'brand-foreground'
          | 'brand'
          | 'primary'
          | 'primary-foreground'
          | 'secondary'
          | 'secondary-foreground'
          | 'white'
          | 'black'
        )
      | null;
    headingColor?:
      | (
          | 'default'
          | 'foreground'
          | 'brand'
          | 'primary'
          | 'secondary'
          | 'accent'
          | 'muted-foreground'
          | 'white'
          | 'black'
        )
      | null;
  };
  /**
   * Add custom Tailwind classes for advanced styling
   */
  customCSS?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'columns';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneQuarter' | 'oneThird' | 'half' | 'twoThirds' | 'threeQuarters' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Optional anchor ID for deep linking (e.g., "about-us" becomes #about-us)
   */
  blockAnchor?: string | null;
  backgroundColor?: ('none' | 'background' | 'card' | 'muted' | 'accent' | 'brand' | 'primary' | 'secondary') | null;
  /**
   * Control padding around this block
   */
  spacing?: {
    paddingTop?: ('none' | 'small' | 'medium' | 'large' | 'xlarge') | null;
    paddingBottom?: ('none' | 'small' | 'medium' | 'large' | 'xlarge') | null;
  };
  /**
   * Horizontal text alignment for content in this block
   */
  textAlignment?: ('left' | 'center' | 'right' | 'justify') | null;
  /**
   * Control when this block is visible
   */
  visibility?: {
    hidden?: boolean | null;
    /**
     * Block will be visible after this date/time
     */
    publishDate?: string | null;
    /**
     * Block will be hidden after this date/time
     */
    expiryDate?: string | null;
  };
  /**
   * Animation that plays when the block enters the viewport
   */
  animation?: ('none' | 'fadeIn' | 'fadeInUp' | 'fadeInDown' | 'fadeInLeft' | 'fadeInRight' | 'zoomIn') | null;
  /**
   * Override global typography settings for this block
   */
  typography?: {
    fontFamily?:
      | (
          | 'default'
          | 'geist-sans'
          | 'geist-mono'
          | 'inter'
          | 'roboto'
          | 'open-sans'
          | 'lato'
          | 'montserrat'
          | 'playfair-display'
          | 'merriweather'
          | 'poppins'
          | 'raleway'
          | 'source-sans-pro'
        )
      | null;
    headingFont?:
      | (
          | 'default'
          | 'geist-sans'
          | 'geist-mono'
          | 'inter'
          | 'roboto'
          | 'open-sans'
          | 'lato'
          | 'montserrat'
          | 'playfair-display'
          | 'merriweather'
          | 'poppins'
          | 'raleway'
          | 'source-sans-pro'
        )
      | null;
    textColor?:
      | (
          | 'default'
          | 'foreground'
          | 'muted-foreground'
          | 'accent-foreground'
          | 'brand-foreground'
          | 'brand'
          | 'primary'
          | 'primary-foreground'
          | 'secondary'
          | 'secondary-foreground'
          | 'white'
          | 'black'
        )
      | null;
    headingColor?:
      | (
          | 'default'
          | 'foreground'
          | 'brand'
          | 'primary'
          | 'secondary'
          | 'accent'
          | 'muted-foreground'
          | 'white'
          | 'black'
        )
      | null;
  };
  /**
   * Add custom Tailwind classes for advanced styling
   */
  customCSS?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  /**
   * Optional anchor ID for deep linking (e.g., "about-us" becomes #about-us)
   */
  blockAnchor?: string | null;
  backgroundColor?: ('none' | 'background' | 'card' | 'muted' | 'accent' | 'brand' | 'primary' | 'secondary') | null;
  /**
   * Control padding around this block
   */
  spacing?: {
    paddingTop?: ('none' | 'small' | 'medium' | 'large' | 'xlarge') | null;
    paddingBottom?: ('none' | 'small' | 'medium' | 'large' | 'xlarge') | null;
  };
  /**
   * Horizontal text alignment for content in this block
   */
  textAlignment?: ('left' | 'center' | 'right' | 'justify') | null;
  /**
   * Control when this block is visible
   */
  visibility?: {
    hidden?: boolean | null;
    /**
     * Block will be visible after this date/time
     */
    publishDate?: string | null;
    /**
     * Block will be hidden after this date/time
     */
    expiryDate?: string | null;
  };
  /**
   * Animation that plays when the block enters the viewport
   */
  animation?: ('none' | 'fadeIn' | 'fadeInUp' | 'fadeInDown' | 'fadeInLeft' | 'fadeInRight' | 'zoomIn') | null;
  /**
   * Override global typography settings for this block
   */
  typography?: {
    fontFamily?:
      | (
          | 'default'
          | 'geist-sans'
          | 'geist-mono'
          | 'inter'
          | 'roboto'
          | 'open-sans'
          | 'lato'
          | 'montserrat'
          | 'playfair-display'
          | 'merriweather'
          | 'poppins'
          | 'raleway'
          | 'source-sans-pro'
        )
      | null;
    headingFont?:
      | (
          | 'default'
          | 'geist-sans'
          | 'geist-mono'
          | 'inter'
          | 'roboto'
          | 'open-sans'
          | 'lato'
          | 'montserrat'
          | 'playfair-display'
          | 'merriweather'
          | 'poppins'
          | 'raleway'
          | 'source-sans-pro'
        )
      | null;
    textColor?:
      | (
          | 'default'
          | 'foreground'
          | 'muted-foreground'
          | 'accent-foreground'
          | 'brand-foreground'
          | 'brand'
          | 'primary'
          | 'primary-foreground'
          | 'secondary'
          | 'secondary-foreground'
          | 'white'
          | 'black'
        )
      | null;
    headingColor?:
      | (
          | 'default'
          | 'foreground'
          | 'brand'
          | 'primary'
          | 'secondary'
          | 'accent'
          | 'muted-foreground'
          | 'white'
          | 'black'
        )
      | null;
  };
  /**
   * Add custom Tailwind classes for advanced styling
   */
  customCSS?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  /**
   * Optional anchor ID for deep linking (e.g., "about-us" becomes #about-us)
   */
  blockAnchor?: string | null;
  backgroundColor?: ('none' | 'background' | 'card' | 'muted' | 'accent' | 'brand' | 'primary' | 'secondary') | null;
  /**
   * Control padding around this block
   */
  spacing?: {
    paddingTop?: ('none' | 'small' | 'medium' | 'large' | 'xlarge') | null;
    paddingBottom?: ('none' | 'small' | 'medium' | 'large' | 'xlarge') | null;
  };
  /**
   * Horizontal text alignment for content in this block
   */
  textAlignment?: ('left' | 'center' | 'right' | 'justify') | null;
  /**
   * Control when this block is visible
   */
  visibility?: {
    hidden?: boolean | null;
    /**
     * Block will be visible after this date/time
     */
    publishDate?: string | null;
    /**
     * Block will be hidden after this date/time
     */
    expiryDate?: string | null;
  };
  /**
   * Animation that plays when the block enters the viewport
   */
  animation?: ('none' | 'fadeIn' | 'fadeInUp' | 'fadeInDown' | 'fadeInLeft' | 'fadeInRight' | 'zoomIn') | null;
  /**
   * Override global typography settings for this block
   */
  typography?: {
    fontFamily?:
      | (
          | 'default'
          | 'geist-sans'
          | 'geist-mono'
          | 'inter'
          | 'roboto'
          | 'open-sans'
          | 'lato'
          | 'montserrat'
          | 'playfair-display'
          | 'merriweather'
          | 'poppins'
          | 'raleway'
          | 'source-sans-pro'
        )
      | null;
    headingFont?:
      | (
          | 'default'
          | 'geist-sans'
          | 'geist-mono'
          | 'inter'
          | 'roboto'
          | 'open-sans'
          | 'lato'
          | 'montserrat'
          | 'playfair-display'
          | 'merriweather'
          | 'poppins'
          | 'raleway'
          | 'source-sans-pro'
        )
      | null;
    textColor?:
      | (
          | 'default'
          | 'foreground'
          | 'muted-foreground'
          | 'accent-foreground'
          | 'brand-foreground'
          | 'brand'
          | 'primary'
          | 'primary-foreground'
          | 'secondary'
          | 'secondary-foreground'
          | 'white'
          | 'black'
        )
      | null;
    headingColor?:
      | (
          | 'default'
          | 'foreground'
          | 'brand'
          | 'primary'
          | 'secondary'
          | 'accent'
          | 'muted-foreground'
          | 'white'
          | 'black'
        )
      | null;
  };
  /**
   * Add custom Tailwind classes for advanced styling
   */
  customCSS?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional anchor ID for deep linking (e.g., "about-us" becomes #about-us)
   */
  blockAnchor?: string | null;
  backgroundColor?: ('none' | 'background' | 'card' | 'muted' | 'accent' | 'brand' | 'primary' | 'secondary') | null;
  /**
   * Control padding around this block
   */
  spacing?: {
    paddingTop?: ('none' | 'small' | 'medium' | 'large' | 'xlarge') | null;
    paddingBottom?: ('none' | 'small' | 'medium' | 'large' | 'xlarge') | null;
  };
  /**
   * Horizontal text alignment for content in this block
   */
  textAlignment?: ('left' | 'center' | 'right' | 'justify') | null;
  /**
   * Control when this block is visible
   */
  visibility?: {
    hidden?: boolean | null;
    /**
     * Block will be visible after this date/time
     */
    publishDate?: string | null;
    /**
     * Block will be hidden after this date/time
     */
    expiryDate?: string | null;
  };
  /**
   * Animation that plays when the block enters the viewport
   */
  animation?: ('none' | 'fadeIn' | 'fadeInUp' | 'fadeInDown' | 'fadeInLeft' | 'fadeInRight' | 'zoomIn') | null;
  /**
   * Override global typography settings for this block
   */
  typography?: {
    fontFamily?:
      | (
          | 'default'
          | 'geist-sans'
          | 'geist-mono'
          | 'inter'
          | 'roboto'
          | 'open-sans'
          | 'lato'
          | 'montserrat'
          | 'playfair-display'
          | 'merriweather'
          | 'poppins'
          | 'raleway'
          | 'source-sans-pro'
        )
      | null;
    headingFont?:
      | (
          | 'default'
          | 'geist-sans'
          | 'geist-mono'
          | 'inter'
          | 'roboto'
          | 'open-sans'
          | 'lato'
          | 'montserrat'
          | 'playfair-display'
          | 'merriweather'
          | 'poppins'
          | 'raleway'
          | 'source-sans-pro'
        )
      | null;
    textColor?:
      | (
          | 'default'
          | 'foreground'
          | 'muted-foreground'
          | 'accent-foreground'
          | 'brand-foreground'
          | 'brand'
          | 'primary'
          | 'primary-foreground'
          | 'secondary'
          | 'secondary-foreground'
          | 'white'
          | 'black'
        )
      | null;
    headingColor?:
      | (
          | 'default'
          | 'foreground'
          | 'brand'
          | 'primary'
          | 'secondary'
          | 'accent'
          | 'muted-foreground'
          | 'white'
          | 'black'
        )
      | null;
  };
  /**
   * Add custom Tailwind classes for advanced styling
   */
  customCSS?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlock".
 */
export interface VideoBlock {
  videoType: 'embed' | 'upload';
  /**
   * YouTube or Vimeo URL (e.g., https://www.youtube.com/watch?v=...)
   */
  embedURL?: string | null;
  videoFile?: (number | null) | Media;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  aspectRatio?: ('16/9' | '4/3' | '1/1' | '21/9') | null;
  autoplay?: boolean | null;
  loop?: boolean | null;
  /**
   * Required for autoplay to work in most browsers
   */
  muted?: boolean | null;
  /**
   * Optional anchor ID for deep linking (e.g., "about-us" becomes #about-us)
   */
  blockAnchor?: string | null;
  backgroundColor?: ('none' | 'background' | 'card' | 'muted' | 'accent' | 'brand' | 'primary' | 'secondary') | null;
  /**
   * Control padding around this block
   */
  spacing?: {
    paddingTop?: ('none' | 'small' | 'medium' | 'large' | 'xlarge') | null;
    paddingBottom?: ('none' | 'small' | 'medium' | 'large' | 'xlarge') | null;
  };
  /**
   * Horizontal text alignment for content in this block
   */
  textAlignment?: ('left' | 'center' | 'right' | 'justify') | null;
  /**
   * Control when this block is visible
   */
  visibility?: {
    hidden?: boolean | null;
    /**
     * Block will be visible after this date/time
     */
    publishDate?: string | null;
    /**
     * Block will be hidden after this date/time
     */
    expiryDate?: string | null;
  };
  /**
   * Animation that plays when the block enters the viewport
   */
  animation?: ('none' | 'fadeIn' | 'fadeInUp' | 'fadeInDown' | 'fadeInLeft' | 'fadeInRight' | 'zoomIn') | null;
  /**
   * Override global typography settings for this block
   */
  typography?: {
    fontFamily?:
      | (
          | 'default'
          | 'geist-sans'
          | 'geist-mono'
          | 'inter'
          | 'roboto'
          | 'open-sans'
          | 'lato'
          | 'montserrat'
          | 'playfair-display'
          | 'merriweather'
          | 'poppins'
          | 'raleway'
          | 'source-sans-pro'
        )
      | null;
    headingFont?:
      | (
          | 'default'
          | 'geist-sans'
          | 'geist-mono'
          | 'inter'
          | 'roboto'
          | 'open-sans'
          | 'lato'
          | 'montserrat'
          | 'playfair-display'
          | 'merriweather'
          | 'poppins'
          | 'raleway'
          | 'source-sans-pro'
        )
      | null;
    textColor?:
      | (
          | 'default'
          | 'foreground'
          | 'muted-foreground'
          | 'accent-foreground'
          | 'brand-foreground'
          | 'brand'
          | 'primary'
          | 'primary-foreground'
          | 'secondary'
          | 'secondary-foreground'
          | 'white'
          | 'black'
        )
      | null;
    headingColor?:
      | (
          | 'default'
          | 'foreground'
          | 'brand'
          | 'primary'
          | 'secondary'
          | 'accent'
          | 'muted-foreground'
          | 'white'
          | 'black'
        )
      | null;
  };
  /**
   * Add custom Tailwind classes for advanced styling
   */
  customCSS?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'video';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  heading?: string | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  testimonials?:
    | {
        quote: string;
        author: string;
        role?: string | null;
        company?: string | null;
        avatar?: (number | null) | Media;
        /**
         * Optional star rating
         */
        rating?: number | null;
        id?: string | null;
      }[]
    | null;
  layout?: ('grid' | 'carousel' | 'featured') | null;
  /**
   * Optional anchor ID for deep linking (e.g., "about-us" becomes #about-us)
   */
  blockAnchor?: string | null;
  backgroundColor?: ('none' | 'background' | 'card' | 'muted' | 'accent' | 'brand' | 'primary' | 'secondary') | null;
  /**
   * Control padding around this block
   */
  spacing?: {
    paddingTop?: ('none' | 'small' | 'medium' | 'large' | 'xlarge') | null;
    paddingBottom?: ('none' | 'small' | 'medium' | 'large' | 'xlarge') | null;
  };
  /**
   * Horizontal text alignment for content in this block
   */
  textAlignment?: ('left' | 'center' | 'right' | 'justify') | null;
  /**
   * Control when this block is visible
   */
  visibility?: {
    hidden?: boolean | null;
    /**
     * Block will be visible after this date/time
     */
    publishDate?: string | null;
    /**
     * Block will be hidden after this date/time
     */
    expiryDate?: string | null;
  };
  /**
   * Animation that plays when the block enters the viewport
   */
  animation?: ('none' | 'fadeIn' | 'fadeInUp' | 'fadeInDown' | 'fadeInLeft' | 'fadeInRight' | 'zoomIn') | null;
  /**
   * Override global typography settings for this block
   */
  typography?: {
    fontFamily?:
      | (
          | 'default'
          | 'geist-sans'
          | 'geist-mono'
          | 'inter'
          | 'roboto'
          | 'open-sans'
          | 'lato'
          | 'montserrat'
          | 'playfair-display'
          | 'merriweather'
          | 'poppins'
          | 'raleway'
          | 'source-sans-pro'
        )
      | null;
    headingFont?:
      | (
          | 'default'
          | 'geist-sans'
          | 'geist-mono'
          | 'inter'
          | 'roboto'
          | 'open-sans'
          | 'lato'
          | 'montserrat'
          | 'playfair-display'
          | 'merriweather'
          | 'poppins'
          | 'raleway'
          | 'source-sans-pro'
        )
      | null;
    textColor?:
      | (
          | 'default'
          | 'foreground'
          | 'muted-foreground'
          | 'accent-foreground'
          | 'brand-foreground'
          | 'brand'
          | 'primary'
          | 'primary-foreground'
          | 'secondary'
          | 'secondary-foreground'
          | 'white'
          | 'black'
        )
      | null;
    headingColor?:
      | (
          | 'default'
          | 'foreground'
          | 'brand'
          | 'primary'
          | 'secondary'
          | 'accent'
          | 'muted-foreground'
          | 'white'
          | 'black'
        )
      | null;
  };
  /**
   * Add custom Tailwind classes for advanced styling
   */
  customCSS?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TabsAccordionBlock".
 */
export interface TabsAccordionBlock {
  heading?: string | null;
  displayMode: 'tabs' | 'accordion' | 'responsive';
  items?:
    | {
        label: string;
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Which item should be open by default? (0 = first item, 1 = second, etc.)
   */
  defaultOpen?: number | null;
  allowMultiple?: boolean | null;
  /**
   * Optional anchor ID for deep linking (e.g., "about-us" becomes #about-us)
   */
  blockAnchor?: string | null;
  backgroundColor?: ('none' | 'background' | 'card' | 'muted' | 'accent' | 'brand' | 'primary' | 'secondary') | null;
  /**
   * Control padding around this block
   */
  spacing?: {
    paddingTop?: ('none' | 'small' | 'medium' | 'large' | 'xlarge') | null;
    paddingBottom?: ('none' | 'small' | 'medium' | 'large' | 'xlarge') | null;
  };
  /**
   * Horizontal text alignment for content in this block
   */
  textAlignment?: ('left' | 'center' | 'right' | 'justify') | null;
  /**
   * Control when this block is visible
   */
  visibility?: {
    hidden?: boolean | null;
    /**
     * Block will be visible after this date/time
     */
    publishDate?: string | null;
    /**
     * Block will be hidden after this date/time
     */
    expiryDate?: string | null;
  };
  /**
   * Animation that plays when the block enters the viewport
   */
  animation?: ('none' | 'fadeIn' | 'fadeInUp' | 'fadeInDown' | 'fadeInLeft' | 'fadeInRight' | 'zoomIn') | null;
  /**
   * Override global typography settings for this block
   */
  typography?: {
    fontFamily?:
      | (
          | 'default'
          | 'geist-sans'
          | 'geist-mono'
          | 'inter'
          | 'roboto'
          | 'open-sans'
          | 'lato'
          | 'montserrat'
          | 'playfair-display'
          | 'merriweather'
          | 'poppins'
          | 'raleway'
          | 'source-sans-pro'
        )
      | null;
    headingFont?:
      | (
          | 'default'
          | 'geist-sans'
          | 'geist-mono'
          | 'inter'
          | 'roboto'
          | 'open-sans'
          | 'lato'
          | 'montserrat'
          | 'playfair-display'
          | 'merriweather'
          | 'poppins'
          | 'raleway'
          | 'source-sans-pro'
        )
      | null;
    textColor?:
      | (
          | 'default'
          | 'foreground'
          | 'muted-foreground'
          | 'accent-foreground'
          | 'brand-foreground'
          | 'brand'
          | 'primary'
          | 'primary-foreground'
          | 'secondary'
          | 'secondary-foreground'
          | 'white'
          | 'black'
        )
      | null;
    headingColor?:
      | (
          | 'default'
          | 'foreground'
          | 'brand'
          | 'primary'
          | 'secondary'
          | 'accent'
          | 'muted-foreground'
          | 'white'
          | 'black'
        )
      | null;
  };
  /**
   * Add custom Tailwind classes for advanced styling
   */
  customCSS?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'tabsAccordion';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock".
 */
export interface StatsBlock {
  heading?: string | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  stats?:
    | {
        /**
         * The number or value (e.g., "100", "99%", "$5M")
         */
        value: string;
        /**
         * What this statistic represents
         */
        label: string;
        /**
         * Optional additional context
         */
        description?: string | null;
        icon?: ('none' | 'users' | 'star' | 'chart' | 'trophy' | 'lightning' | 'globe' | 'heart' | 'rocket') | null;
        /**
         * Animate counting up to the value
         */
        animate?: boolean | null;
        id?: string | null;
      }[]
    | null;
  layout?: ('grid-2' | 'grid-3' | 'grid-4' | 'horizontal') | null;
  /**
   * Optional anchor ID for deep linking (e.g., "about-us" becomes #about-us)
   */
  blockAnchor?: string | null;
  backgroundColor?: ('none' | 'background' | 'card' | 'muted' | 'accent' | 'brand' | 'primary' | 'secondary') | null;
  /**
   * Control padding around this block
   */
  spacing?: {
    paddingTop?: ('none' | 'small' | 'medium' | 'large' | 'xlarge') | null;
    paddingBottom?: ('none' | 'small' | 'medium' | 'large' | 'xlarge') | null;
  };
  /**
   * Horizontal text alignment for content in this block
   */
  textAlignment?: ('left' | 'center' | 'right' | 'justify') | null;
  /**
   * Control when this block is visible
   */
  visibility?: {
    hidden?: boolean | null;
    /**
     * Block will be visible after this date/time
     */
    publishDate?: string | null;
    /**
     * Block will be hidden after this date/time
     */
    expiryDate?: string | null;
  };
  /**
   * Animation that plays when the block enters the viewport
   */
  animation?: ('none' | 'fadeIn' | 'fadeInUp' | 'fadeInDown' | 'fadeInLeft' | 'fadeInRight' | 'zoomIn') | null;
  /**
   * Override global typography settings for this block
   */
  typography?: {
    fontFamily?:
      | (
          | 'default'
          | 'geist-sans'
          | 'geist-mono'
          | 'inter'
          | 'roboto'
          | 'open-sans'
          | 'lato'
          | 'montserrat'
          | 'playfair-display'
          | 'merriweather'
          | 'poppins'
          | 'raleway'
          | 'source-sans-pro'
        )
      | null;
    headingFont?:
      | (
          | 'default'
          | 'geist-sans'
          | 'geist-mono'
          | 'inter'
          | 'roboto'
          | 'open-sans'
          | 'lato'
          | 'montserrat'
          | 'playfair-display'
          | 'merriweather'
          | 'poppins'
          | 'raleway'
          | 'source-sans-pro'
        )
      | null;
    textColor?:
      | (
          | 'default'
          | 'foreground'
          | 'muted-foreground'
          | 'accent-foreground'
          | 'brand-foreground'
          | 'brand'
          | 'primary'
          | 'primary-foreground'
          | 'secondary'
          | 'secondary-foreground'
          | 'white'
          | 'black'
        )
      | null;
    headingColor?:
      | (
          | 'default'
          | 'foreground'
          | 'brand'
          | 'primary'
          | 'secondary'
          | 'accent'
          | 'muted-foreground'
          | 'white'
          | 'black'
        )
      | null;
  };
  /**
   * Add custom Tailwind classes for advanced styling
   */
  customCSS?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock".
 */
export interface TimelineBlock {
  heading?: string | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  items?:
    | {
        /**
         * e.g., "2024", "Q1 2024", "January 2024"
         */
        date: string;
        title: string;
        description?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        image?: (number | null) | Media;
        icon?: ('none' | 'check' | 'star' | 'flag' | 'lightbulb' | 'rocket' | 'calendar') | null;
        id?: string | null;
      }[]
    | null;
  layout?: ('vertical' | 'vertical-center' | 'horizontal') | null;
  /**
   * Optional anchor ID for deep linking (e.g., "about-us" becomes #about-us)
   */
  blockAnchor?: string | null;
  backgroundColor?: ('none' | 'background' | 'card' | 'muted' | 'accent' | 'brand' | 'primary' | 'secondary') | null;
  /**
   * Control padding around this block
   */
  spacing?: {
    paddingTop?: ('none' | 'small' | 'medium' | 'large' | 'xlarge') | null;
    paddingBottom?: ('none' | 'small' | 'medium' | 'large' | 'xlarge') | null;
  };
  /**
   * Horizontal text alignment for content in this block
   */
  textAlignment?: ('left' | 'center' | 'right' | 'justify') | null;
  /**
   * Control when this block is visible
   */
  visibility?: {
    hidden?: boolean | null;
    /**
     * Block will be visible after this date/time
     */
    publishDate?: string | null;
    /**
     * Block will be hidden after this date/time
     */
    expiryDate?: string | null;
  };
  /**
   * Animation that plays when the block enters the viewport
   */
  animation?: ('none' | 'fadeIn' | 'fadeInUp' | 'fadeInDown' | 'fadeInLeft' | 'fadeInRight' | 'zoomIn') | null;
  /**
   * Override global typography settings for this block
   */
  typography?: {
    fontFamily?:
      | (
          | 'default'
          | 'geist-sans'
          | 'geist-mono'
          | 'inter'
          | 'roboto'
          | 'open-sans'
          | 'lato'
          | 'montserrat'
          | 'playfair-display'
          | 'merriweather'
          | 'poppins'
          | 'raleway'
          | 'source-sans-pro'
        )
      | null;
    headingFont?:
      | (
          | 'default'
          | 'geist-sans'
          | 'geist-mono'
          | 'inter'
          | 'roboto'
          | 'open-sans'
          | 'lato'
          | 'montserrat'
          | 'playfair-display'
          | 'merriweather'
          | 'poppins'
          | 'raleway'
          | 'source-sans-pro'
        )
      | null;
    textColor?:
      | (
          | 'default'
          | 'foreground'
          | 'muted-foreground'
          | 'accent-foreground'
          | 'brand-foreground'
          | 'brand'
          | 'primary'
          | 'primary-foreground'
          | 'secondary'
          | 'secondary-foreground'
          | 'white'
          | 'black'
        )
      | null;
    headingColor?:
      | (
          | 'default'
          | 'foreground'
          | 'brand'
          | 'primary'
          | 'secondary'
          | 'accent'
          | 'muted-foreground'
          | 'white'
          | 'black'
        )
      | null;
  };
  /**
   * Add custom Tailwind classes for advanced styling
   */
  customCSS?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'timeline';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Optional anchor ID for deep linking (e.g., "about-us" becomes #about-us)
   */
  blockAnchor?: string | null;
  backgroundColor?: ('none' | 'background' | 'card' | 'muted' | 'accent' | 'brand' | 'primary' | 'secondary') | null;
  /**
   * Control padding around this block
   */
  spacing?: {
    paddingTop?: ('none' | 'small' | 'medium' | 'large' | 'xlarge') | null;
    paddingBottom?: ('none' | 'small' | 'medium' | 'large' | 'xlarge') | null;
  };
  /**
   * Horizontal text alignment for content in this block
   */
  textAlignment?: ('left' | 'center' | 'right' | 'justify') | null;
  /**
   * Control when this block is visible
   */
  visibility?: {
    hidden?: boolean | null;
    /**
     * Block will be visible after this date/time
     */
    publishDate?: string | null;
    /**
     * Block will be hidden after this date/time
     */
    expiryDate?: string | null;
  };
  /**
   * Animation that plays when the block enters the viewport
   */
  animation?: ('none' | 'fadeIn' | 'fadeInUp' | 'fadeInDown' | 'fadeInLeft' | 'fadeInRight' | 'zoomIn') | null;
  /**
   * Override global typography settings for this block
   */
  typography?: {
    fontFamily?:
      | (
          | 'default'
          | 'geist-sans'
          | 'geist-mono'
          | 'inter'
          | 'roboto'
          | 'open-sans'
          | 'lato'
          | 'montserrat'
          | 'playfair-display'
          | 'merriweather'
          | 'poppins'
          | 'raleway'
          | 'source-sans-pro'
        )
      | null;
    headingFont?:
      | (
          | 'default'
          | 'geist-sans'
          | 'geist-mono'
          | 'inter'
          | 'roboto'
          | 'open-sans'
          | 'lato'
          | 'montserrat'
          | 'playfair-display'
          | 'merriweather'
          | 'poppins'
          | 'raleway'
          | 'source-sans-pro'
        )
      | null;
    textColor?:
      | (
          | 'default'
          | 'foreground'
          | 'muted-foreground'
          | 'accent-foreground'
          | 'brand-foreground'
          | 'brand'
          | 'primary'
          | 'primary-foreground'
          | 'secondary'
          | 'secondary-foreground'
          | 'white'
          | 'black'
        )
      | null;
    headingColor?:
      | (
          | 'default'
          | 'foreground'
          | 'brand'
          | 'primary'
          | 'secondary'
          | 'accent'
          | 'muted-foreground'
          | 'white'
          | 'black'
        )
      | null;
  };
  /**
   * Add custom Tailwind classes for advanced styling
   */
  customCSS?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  /**
   * Optional anchor ID for deep linking (e.g., "about-us" becomes #about-us)
   */
  blockAnchor?: string | null;
  backgroundColor?: ('none' | 'background' | 'card' | 'muted' | 'accent' | 'brand' | 'primary' | 'secondary') | null;
  /**
   * Control padding around this block
   */
  spacing?: {
    paddingTop?: ('none' | 'small' | 'medium' | 'large' | 'xlarge') | null;
    paddingBottom?: ('none' | 'small' | 'medium' | 'large' | 'xlarge') | null;
  };
  /**
   * Horizontal text alignment for content in this block
   */
  textAlignment?: ('left' | 'center' | 'right' | 'justify') | null;
  /**
   * Control when this block is visible
   */
  visibility?: {
    hidden?: boolean | null;
    /**
     * Block will be visible after this date/time
     */
    publishDate?: string | null;
    /**
     * Block will be hidden after this date/time
     */
    expiryDate?: string | null;
  };
  /**
   * Animation that plays when the block enters the viewport
   */
  animation?: ('none' | 'fadeIn' | 'fadeInUp' | 'fadeInDown' | 'fadeInLeft' | 'fadeInRight' | 'zoomIn') | null;
  /**
   * Override global typography settings for this block
   */
  typography?: {
    fontFamily?:
      | (
          | 'default'
          | 'geist-sans'
          | 'geist-mono'
          | 'inter'
          | 'roboto'
          | 'open-sans'
          | 'lato'
          | 'montserrat'
          | 'playfair-display'
          | 'merriweather'
          | 'poppins'
          | 'raleway'
          | 'source-sans-pro'
        )
      | null;
    headingFont?:
      | (
          | 'default'
          | 'geist-sans'
          | 'geist-mono'
          | 'inter'
          | 'roboto'
          | 'open-sans'
          | 'lato'
          | 'montserrat'
          | 'playfair-display'
          | 'merriweather'
          | 'poppins'
          | 'raleway'
          | 'source-sans-pro'
        )
      | null;
    textColor?:
      | (
          | 'default'
          | 'foreground'
          | 'muted-foreground'
          | 'accent-foreground'
          | 'brand-foreground'
          | 'brand'
          | 'primary'
          | 'primary-foreground'
          | 'secondary'
          | 'secondary-foreground'
          | 'white'
          | 'black'
        )
      | null;
    headingColor?:
      | (
          | 'default'
          | 'foreground'
          | 'brand'
          | 'primary'
          | 'secondary'
          | 'accent'
          | 'muted-foreground'
          | 'white'
          | 'black'
        )
      | null;
  };
  /**
   * Add custom Tailwind classes for advanced styling
   */
  customCSS?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * Create reusable blocks that can be referenced across multiple pages
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blocks".
 */
export interface Block {
  id: number;
  /**
   * A descriptive name to identify this block
   */
  name: string;
  /**
   * Optional description of what this block is used for
   */
  description?: string | null;
  block: (
    | CallToActionBlock
    | ContentBlock
    | MediaBlock
    | ArchiveBlock
    | FormBlock
    | VideoBlock
    | TestimonialsBlock
    | TabsAccordionBlock
    | StatsBlock
    | TimelineBlock
    | BannerBlock
    | CodeBlock
  )[];
  /**
   * Categorize this block for easier filtering
   */
  category?: ('cta' | 'content' | 'media' | 'interactive' | 'social-proof' | 'forms' | 'other') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: number | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'blocks';
        value: number | Block;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-jobs';
        value: number | PayloadJob;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        height?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        columns?: T | ColumnsBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        video?: T | VideoBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        tabsAccordion?: T | TabsAccordionBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        timeline?: T | TimelineBlockSelect<T>;
        banner?: T | BannerBlockSelect<T>;
        code?: T | CodeBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  blockAnchor?: T;
  backgroundColor?: T;
  spacing?:
    | T
    | {
        paddingTop?: T;
        paddingBottom?: T;
      };
  textAlignment?: T;
  visibility?:
    | T
    | {
        hidden?: T;
        publishDate?: T;
        expiryDate?: T;
      };
  animation?: T;
  typography?:
    | T
    | {
        fontFamily?: T;
        headingFont?: T;
        textColor?: T;
        headingColor?: T;
      };
  customCSS?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ColumnsBlock_select".
 */
export interface ColumnsBlockSelect<T extends boolean = true> {
  layout?: T;
  reverseOnMobile?: T;
  gap?: T;
  columns?:
    | T
    | {
        contentType?: T;
        richText?: T;
        media?: T;
        caption?: T;
        videoType?: T;
        videoUrl?: T;
        videoUpload?: T;
        code?: T;
        language?: T;
        customHTML?: T;
        ctaText?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        verticalAlignment?: T;
        textAlign?: T;
        padding?: T;
        id?: T;
      };
  blockAnchor?: T;
  backgroundColor?: T;
  spacing?:
    | T
    | {
        paddingTop?: T;
        paddingBottom?: T;
      };
  textAlignment?: T;
  visibility?:
    | T
    | {
        hidden?: T;
        publishDate?: T;
        expiryDate?: T;
      };
  animation?: T;
  typography?:
    | T
    | {
        fontFamily?: T;
        headingFont?: T;
        textColor?: T;
        headingColor?: T;
      };
  customCSS?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  blockAnchor?: T;
  backgroundColor?: T;
  spacing?:
    | T
    | {
        paddingTop?: T;
        paddingBottom?: T;
      };
  textAlignment?: T;
  visibility?:
    | T
    | {
        hidden?: T;
        publishDate?: T;
        expiryDate?: T;
      };
  animation?: T;
  typography?:
    | T
    | {
        fontFamily?: T;
        headingFont?: T;
        textColor?: T;
        headingColor?: T;
      };
  customCSS?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  blockAnchor?: T;
  backgroundColor?: T;
  spacing?:
    | T
    | {
        paddingTop?: T;
        paddingBottom?: T;
      };
  textAlignment?: T;
  visibility?:
    | T
    | {
        hidden?: T;
        publishDate?: T;
        expiryDate?: T;
      };
  animation?: T;
  typography?:
    | T
    | {
        fontFamily?: T;
        headingFont?: T;
        textColor?: T;
        headingColor?: T;
      };
  customCSS?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  blockAnchor?: T;
  backgroundColor?: T;
  spacing?:
    | T
    | {
        paddingTop?: T;
        paddingBottom?: T;
      };
  textAlignment?: T;
  visibility?:
    | T
    | {
        hidden?: T;
        publishDate?: T;
        expiryDate?: T;
      };
  animation?: T;
  typography?:
    | T
    | {
        fontFamily?: T;
        headingFont?: T;
        textColor?: T;
        headingColor?: T;
      };
  customCSS?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  blockAnchor?: T;
  backgroundColor?: T;
  spacing?:
    | T
    | {
        paddingTop?: T;
        paddingBottom?: T;
      };
  textAlignment?: T;
  visibility?:
    | T
    | {
        hidden?: T;
        publishDate?: T;
        expiryDate?: T;
      };
  animation?: T;
  typography?:
    | T
    | {
        fontFamily?: T;
        headingFont?: T;
        textColor?: T;
        headingColor?: T;
      };
  customCSS?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlock_select".
 */
export interface VideoBlockSelect<T extends boolean = true> {
  videoType?: T;
  embedURL?: T;
  videoFile?: T;
  caption?: T;
  aspectRatio?: T;
  autoplay?: T;
  loop?: T;
  muted?: T;
  blockAnchor?: T;
  backgroundColor?: T;
  spacing?:
    | T
    | {
        paddingTop?: T;
        paddingBottom?: T;
      };
  textAlignment?: T;
  visibility?:
    | T
    | {
        hidden?: T;
        publishDate?: T;
        expiryDate?: T;
      };
  animation?: T;
  typography?:
    | T
    | {
        fontFamily?: T;
        headingFont?: T;
        textColor?: T;
        headingColor?: T;
      };
  customCSS?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  heading?: T;
  introContent?: T;
  testimonials?:
    | T
    | {
        quote?: T;
        author?: T;
        role?: T;
        company?: T;
        avatar?: T;
        rating?: T;
        id?: T;
      };
  layout?: T;
  blockAnchor?: T;
  backgroundColor?: T;
  spacing?:
    | T
    | {
        paddingTop?: T;
        paddingBottom?: T;
      };
  textAlignment?: T;
  visibility?:
    | T
    | {
        hidden?: T;
        publishDate?: T;
        expiryDate?: T;
      };
  animation?: T;
  typography?:
    | T
    | {
        fontFamily?: T;
        headingFont?: T;
        textColor?: T;
        headingColor?: T;
      };
  customCSS?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TabsAccordionBlock_select".
 */
export interface TabsAccordionBlockSelect<T extends boolean = true> {
  heading?: T;
  displayMode?: T;
  items?:
    | T
    | {
        label?: T;
        content?: T;
        id?: T;
      };
  defaultOpen?: T;
  allowMultiple?: T;
  blockAnchor?: T;
  backgroundColor?: T;
  spacing?:
    | T
    | {
        paddingTop?: T;
        paddingBottom?: T;
      };
  textAlignment?: T;
  visibility?:
    | T
    | {
        hidden?: T;
        publishDate?: T;
        expiryDate?: T;
      };
  animation?: T;
  typography?:
    | T
    | {
        fontFamily?: T;
        headingFont?: T;
        textColor?: T;
        headingColor?: T;
      };
  customCSS?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock_select".
 */
export interface StatsBlockSelect<T extends boolean = true> {
  heading?: T;
  introContent?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        description?: T;
        icon?: T;
        animate?: T;
        id?: T;
      };
  layout?: T;
  blockAnchor?: T;
  backgroundColor?: T;
  spacing?:
    | T
    | {
        paddingTop?: T;
        paddingBottom?: T;
      };
  textAlignment?: T;
  visibility?:
    | T
    | {
        hidden?: T;
        publishDate?: T;
        expiryDate?: T;
      };
  animation?: T;
  typography?:
    | T
    | {
        fontFamily?: T;
        headingFont?: T;
        textColor?: T;
        headingColor?: T;
      };
  customCSS?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock_select".
 */
export interface TimelineBlockSelect<T extends boolean = true> {
  heading?: T;
  introContent?: T;
  items?:
    | T
    | {
        date?: T;
        title?: T;
        description?: T;
        image?: T;
        icon?: T;
        id?: T;
      };
  layout?: T;
  blockAnchor?: T;
  backgroundColor?: T;
  spacing?:
    | T
    | {
        paddingTop?: T;
        paddingBottom?: T;
      };
  textAlignment?: T;
  visibility?:
    | T
    | {
        hidden?: T;
        publishDate?: T;
        expiryDate?: T;
      };
  animation?: T;
  typography?:
    | T
    | {
        fontFamily?: T;
        headingFont?: T;
        textColor?: T;
        headingColor?: T;
      };
  customCSS?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock_select".
 */
export interface BannerBlockSelect<T extends boolean = true> {
  style?: T;
  content?: T;
  blockAnchor?: T;
  backgroundColor?: T;
  spacing?:
    | T
    | {
        paddingTop?: T;
        paddingBottom?: T;
      };
  textAlignment?: T;
  visibility?:
    | T
    | {
        hidden?: T;
        publishDate?: T;
        expiryDate?: T;
      };
  animation?: T;
  typography?:
    | T
    | {
        fontFamily?: T;
        headingFont?: T;
        textColor?: T;
        headingColor?: T;
      };
  customCSS?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock_select".
 */
export interface CodeBlockSelect<T extends boolean = true> {
  language?: T;
  code?: T;
  blockAnchor?: T;
  backgroundColor?: T;
  spacing?:
    | T
    | {
        paddingTop?: T;
        paddingBottom?: T;
      };
  textAlignment?: T;
  visibility?:
    | T
    | {
        hidden?: T;
        publishDate?: T;
        expiryDate?: T;
      };
  animation?: T;
  typography?:
    | T
    | {
        fontFamily?: T;
        headingFont?: T;
        textColor?: T;
        headingColor?: T;
      };
  customCSS?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  optimization?:
    | T
    | {
        priority?: T;
        quality?: T;
        lazyLoad?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blocks_select".
 */
export interface BlocksSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  block?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        video?: T | VideoBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        tabsAccordion?: T | TabsAccordionBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        timeline?: T | TimelineBlockSelect<T>;
        banner?: T | BannerBlockSelect<T>;
        code?: T | CodeBlockSelect<T>;
      };
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  /**
   * Upload your logo to extract colors and generate a theme
   */
  logo?: (number | null) | Media;
  /**
   * Hex code (e.g., #3B82F6) - Can be extracted from logo or manually set
   */
  primaryBrandColor?: string | null;
  /**
   * Hex code for secondary/accent color
   */
  secondaryBrandColor?: string | null;
  /**
   * Hex code for accent elements (buttons, links, etc.)
   */
  accentColor?: string | null;
  /**
   * Hex code for page background
   */
  backgroundColor?: string | null;
  /**
   * Colors extracted from your logo or manually added
   */
  extractedPalette?:
    | {
        /**
         * e.g., "Vibrant", "Muted", "Dark Vibrant"
         */
        colorName?: string | null;
        /**
         * e.g., #FF5733
         */
        hex: string;
        usage?: ('primary' | 'secondary' | 'accent' | 'background' | 'text') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Default font for body text across the site
   */
  defaultFont?:
    | (
        | 'geist-sans'
        | 'geist-mono'
        | 'inter'
        | 'roboto'
        | 'open-sans'
        | 'lato'
        | 'montserrat'
        | 'playfair-display'
        | 'merriweather'
        | 'poppins'
        | 'raleway'
        | 'source-sans-pro'
      )
    | null;
  /**
   * Default font for headings across the site
   */
  headingFont?:
    | (
        | 'geist-sans'
        | 'geist-mono'
        | 'inter'
        | 'roboto'
        | 'open-sans'
        | 'lato'
        | 'montserrat'
        | 'playfair-display'
        | 'merriweather'
        | 'poppins'
        | 'raleway'
        | 'source-sans-pro'
      )
    | null;
  /**
   * Default color for body text
   */
  defaultTextColor?:
    | (
        | 'foreground'
        | 'muted-foreground'
        | 'accent-foreground'
        | 'brand-foreground'
        | 'primary-foreground'
        | 'secondary-foreground'
        | 'white'
        | 'black'
      )
    | null;
  /**
   * Default color for headings
   */
  defaultHeadingColor?:
    | ('foreground' | 'brand' | 'primary' | 'secondary' | 'accent' | 'muted-foreground' | 'white' | 'black')
    | null;
  /**
   * Add custom Google Fonts to use throughout the site
   */
  customGoogleFonts?:
    | {
        /**
         * e.g., "Roboto Slab", "Dancing Script"
         */
        name: string;
        /**
         * URL-friendly name (e.g., "roboto-slab", "dancing-script")
         */
        slug: string;
        /**
         * Comma-separated weights (e.g., "300,400,700")
         */
        weights?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Define custom colors for use in blocks
   */
  customColors?:
    | {
        name: string;
        /**
         * CSS-friendly name (e.g., "custom-blue")
         */
        slug: string;
        /**
         * Hex code (e.g., "#FF5733") or HSL (e.g., "210 40% 50%")
         */
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  logo?: T;
  primaryBrandColor?: T;
  secondaryBrandColor?: T;
  accentColor?: T;
  backgroundColor?: T;
  extractedPalette?:
    | T
    | {
        colorName?: T;
        hex?: T;
        usage?: T;
        id?: T;
      };
  defaultFont?: T;
  headingFont?: T;
  defaultTextColor?: T;
  defaultHeadingColor?: T;
  customGoogleFonts?:
    | T
    | {
        name?: T;
        slug?: T;
        weights?: T;
        id?: T;
      };
  customColors?:
    | T
    | {
        name?: T;
        slug?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}